version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_ROOT_HOST: '%'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq  #默认 guest
      RABBITMQ_DEFAULT_PASS: rabbitmq  #默认 guest
    # RABBITMQ_DEFAULT_VHOST: rabbitmq
    restart: always
  nginx:
    image: openresty/openresty:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
volumes:
  mysql-data:
  redis-data:
  rabbitmq-data: